baseURL = "/"
theme = "aether"
enableRobotsTXT = true
languageCode = "en-gb"
rssLimit = 20

[permalinks]
    posts = "/posts/:year/:month/:day/:title/"

[params]
    rssinmenu = true
    metaCreator = "Simon Li"
    metaImage = "images/ogimage.jpg"

[frontmatter]
    date = ["date", "publishDate", "lastmod"]
    lastmod = [":git", "lastmod", "date", "publishDate"]
    publishDate = ["publishDate", "date"]
    expiryDate = ["expiryDate"]
